import fetch from 'node-fetch';
import { shuffleArray, apiResponse } from './scripts/shuffleArray';
import { reddit } from './credentials.json';
import snoowrap from 'snoowrap';

// Create reddit client
const r = new snoowrap(reddit.user);

export async function getRandomRedditPosts(): Promise<apiResponse> {        
  const text = 'In 1989, Pfizer developed Sildenafil (Viagra) to treat heart-related chest pain.\n' +
  '\n' +
  'From Wikipedia:\n' +
  '\n' +
  "Sildenafil (compound UK-92,480) was synthesized by a group of pharmaceutical chemists working at Pfizer's [Sandwich, Kent](https://en.m.wikipedia.org/wiki/Sandwich,_Kent), research facility in England. It was initially studied for use in [hypertension](https://en.m.wikipedia.org/wiki/Hypertension) (high blood pressure) and [angina pectoris](https://en.m.wikipedia.org/wiki/Angina_pectoris) (a symptom of [ischaemic heart disease](https://en.m.wikipedia.org/wiki/Ischaemic_heart_disease)). The first clinical trials were conducted in [Morriston Hospital](https://en.m.wikipedia.org/wiki/Morriston_Hospital) in [Swansea](https://en.m.wikipedia.org/wiki/Swansea).[[53]](https://en.m.wikipedia.org/wiki/Sildenafil#cite_note-53) Phase I [clinical trials](https://en.m.wikipedia.org/wiki/Clinical_trial) under the direction of [Ian Osterloh](https://en.m.wikipedia.org/wiki/Ian_Osterloh) suggested the drug had little effect on angina, but it could induce marked penile [erections](https://en.m.wikipedia.org/wiki/Erection).[[54]](https://en.m.wikipedia.org/wiki/Sildenafil#cite_note-autogenerated47-54)[[55]](https://en.m.wikipedia.org/wiki/Sildenafil#cite_note-55) Pfizer therefore decided to market it for erectile dysfunction, rather than for angina; this decision became an often-cited example of [drug repositioning](https://en.m.wikipedia.org/wiki/Drug_repositioning).[[56]](https://en.m.wikipedia.org/wiki/Sildenafil#cite_note-56)[[57]](https://en.m.wikipedia.org/wiki/Sildenafil#cite_note-57) The drug was [patented](https://en.m.wikipedia.org/wiki/Patent) in 1996, approved for use in erectile dysfunction by the FDA on 27 March 1998, becoming the first oral treatment approved to treat erectile dysfunction in the United States, and offered for sale in the United States later that year.[[58]](https://en.m.wikipedia.org/wiki/Sildenafil#cite_note-58) It soon became a great success: annual sales of Viagra peaked in 2008 at US$1.934 billion.[[59]](https://en.m.wikipedia.org/wiki/Sildenafil#cite_note-59)"
  
  const apiResponse: apiResponse = {
    text: formatResponse(text),
    link: '',
    indexOfAnswer: 0,
    list: []
  }

  return apiResponse;

  const limit = 100;
  const topPosts = await r.getSubreddit("askReddit").getTop({ time: 'day', limit });

  // Remove NSFW posts
  const filteredPosts = topPosts.filter(post => post.over_18 === false);

  // Get titles from four random posts
  for (let i = 0; i < 4; i++) {
    const index = randomIntegerInRange(0, filteredPosts.length - 1);
    const randomPost = filteredPosts[index];
    filteredPosts.splice(index, 1);

    if (i === 0) {
      apiResponse.link = randomPost.url;
      
      const comments = await randomPost.comments.fetchMore({
        amount: 10,
        skipReplies: true,
      });

      apiResponse.text = comments[randomIntegerInRange(0, comments.length - 1)].body.trim();
      
    }

    // Add title
    apiResponse.list.push(randomPost.title);
  }

  // Shuffle array
  const shuffledObject = shuffleArray(apiResponse.list);
  apiResponse.list = shuffledObject.array;
  apiResponse.indexOfAnswer = shuffledObject.indexOfAnswer;

  return apiResponse;
}

function formatResponse(text: string): string {
  const regex = /\[([^\[]+)\](\(.*\))/gm;
  const splittedText = text.split(' ');

  for (let word of splittedText) {
    if (word.match(regex)) {
      // Word contains a link
      // Get first word in [];
      console.log(word)
    }
  }
  return text;
}

function randomIntegerInRange (min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}